### ISSUE TITLE
Correct a typo in the word "Planetbase" at the top of the program interface

### ISSUE THREAD

**Issue by NeoRider7** [provector/jPBCE#4]
Correct a typo in the word Planetbase at the top of the program interface
Correct the word "Plentbase" to "Planetbase". (A typo is allowed in the word).
This word is located at the very top of the program interface where the name of the program and the version of the program are written.

This typo in the word is visible on all screenshots of the program.
Therefore, it is also advisable to replace all screenshots of the program.

**Comment by provector** [comment]
Resolved in 1.0.I
