### ISSUE TITLE
correct the name of the parameter for the amount of alcoholic beverages.

### ISSUE THREAD

**Issue by NeoRider7** [provector/jPBCE#5]
We need to correct the name of the parameter for the amount of alcoholic beverages.
Now the program produces a line like this: 
 objective type = "AccumulateResources" param = "Alcohol" value = "5" 
This line causes an error loading the challenge.

We need to fix it on another line of this kind:
objective type = "AccumulateResources" param = "AlcoholicDrink" value = "5" 

In other words, we need to correct the word "Alcohol" to another word "AlcoholicDrink".

**Comment by provector** [comment]
Thanks for finding that. Should be fixed with the next update.

**Comment by provector** [comment]
fixed in 1.0.0
