### ISSUE TITLE
ability to set money accumulation

### ISSUE THREAD

**Issue by NeoRider7** [provector/jPBCE#6]
It is necessary to add to the program the ability to set money accumulation as the goal of the challenge.
I did not find such a parameter in the PBCE program.

The line of code for accumulating money should look like this: 
objective type = "AccumulateResources" param = "Coins" value = "1500"

**Comment by provector** [comment]
Spot on! Ill include that in next update.

**Comment by provector** [comment]
Added in 1.0.0
