### ISSUE TITLE
Error in the name of the parameters for the bots

### ISSUE THREAD

**Issue by NeoRider7** [provector/jPBCE#7]
Error in the name of the parameters for the bots.

Correct the word “**CarrierBot**” to the word “**Carrier**”.
Correct the word “**ConstructorBot**” to the word “**Constructor**”.
Correct the word “**DrillerBot**” to the word “**Driller**”.

It should be written correctly like this:
-		starting_specialization type="Driller" amount="0"
-		starting_specialization type="Constructor" amount="0"
-		starting_specialization type="Carrier" amount="0"

Now it is written like this with an error:
- objective type="ReachSpecialization" param="CarrierBot" value="1"
- objective type="ReachSpecialization" param="ConstructorBot" value="1"

**Comment by provector** [comment]
So it's only for the reach Specialization this way? (I remember it working for start params). Seems like API is a bit inconsitent. Anyway should be fixed in next release.

**Comment by provector** [comment]
Fixed in 1.0.0
